name: Hourly Paragraph Check

on:
  schedule:
    # Runs at minute 0 of UTC hours 0–1 and 10–23
    # → corresponds to local Bogotá hours 19:00–20:00 and 05:00–18:00 (i.e. 5 AM–8 PM)
    - cron: '0 0-1,10-23 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run paragraph check
        id: check
        run: python check_site.py
        continue-on-error: true

      - name: Notify on change
        if: steps.check.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          subject:        "🔔 MME Potential Production has changed"
          body:           |
            The monitored paragraph on https://www.minenergia.gov.co/es/misional/hidrocarburos/funcionamiento-del-sector/gas-natural/ has changed.
          to:             ${{ secrets.NOTIFY_EMAIL }}
          bcc:            ${{ secrets.BCC_EMAILS }}
          from:           ${{ secrets.FROM_EMAIL }}

