
name: Hourly Site Check

on:
  schedule:
    - cron: '0 * * * *'    # cada hora, en el minuto 0
  workflow_dispatch:      # permite ejecución manual desde la UI

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run site-check script
        id: check
        run: |
          if python check_site.py; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true"  >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Commit updated snapshot
        if: steps.check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prev_content.html
          git commit -m "🔄 Update site snapshot"
          git push

      - name: Send email notification
        if: steps.check.outputs.changed == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          subject:        "🔔 Site content changed"
          body:           "The monitored section on minenergia.gov.co has changed."
          to:             ${{ secrets.NOTIFY_EMAIL }}
          from:           ${{ secrets.FROM_EMAIL }}
